### ISSUE TITLE
GPL License ?

### ISSUE THREAD

**Issue by alvareap** [shakyShane/easy-extender#2]
GPL License on easy-extender (https://www.npmjs.com/package/easy-extender, and eazy-logger) implies BrowserSync which is supposed to be Apache is de facto GPL.

https://www.gnu.org/copyleft/gpl-faq.html#GPLRequireSourcePostedPublic

**Comment by shakyShane** [comment]
:+1: on it

**Comment by jfstephe** [comment]
Hi,
  Any change this can be fixed + merged?. My client restricts GPL licenses and so I can't use browser-sync as a result :-(. (likewise for easy-logger)
thanks,
  John
